/* AUTH types */
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_USER_ERROR = 'SET_USER_ERROR';
export const LOCAL_SIGN_IN = 'LOCAL_SIGN_IN';
export const USER_LOADING = 'USER_LOADING';

/*Category types */
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const CREATE_CATEGORY_ERROR = 'CREATE_CATEGORY_ERROR';
export const CATEGORY_LOADING = 'CATEGORY_LOADING';
export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const DELETE_SERVICE = 'DELETE_SERVICE';

/*Business types */
export const CREATE_BUSINESS = 'CREATE_BUSINESS';
export const GET_BUSINESS_BY_OWNER = 'GET_BUSINESS_BY_OWNER';
export const GET_BUSINESS_BY_ID = 'GET_BUSINESS_BY_ID';
export const GET_CUREENT_BUSINESS_FOLLOWERS = 'GET_CUREENT_BUSINESS_FOLLOWERS';
export const GET_CUREENT_BUSINESS_SERVICES = 'GET_CUREENT_BUSINESS_SERVICES';
