/* AUTH types */
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_USER_ERROR = 'SET_USER_ERROR';
export const LOCAL_SIGN_IN = 'LOCAL_SIGN_IN';
export const USER_LOADING = 'USER_LOADING';
export const SET_AS_BUSINESS_OWNER = 'SET_AS_BUSINESS_OWNER';

/*Category types */
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const CREATE_CATEGORY_ERROR = 'CREATE_CATEGORY_ERROR';
export const CATEGORY_LOADING = 'CATEGORY_LOADING';
export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const DELETE_SERVICE = 'DELETE_SERVICE';

/*Business types */
export const CREATE_BUSINESS = 'CREATE_BUSINESS';
export const GET_BUSINESS_BY_OWNER = 'GET_BUSINESS_BY_OWNER';
export const GET_BUSINESS_BY_ID = 'GET_BUSINESS_BY_ID';
export const GET_CUREENT_BUSINESS_CUSTOMERS = 'GET_CUREENT_BUSINESS_CUSTOMERS';
export const GET_CUREENT_BUSINESS_SERVICES = 'GET_CUREENT_BUSINESS_SERVICES';
export const FOLLOW_BUSINESS = 'FOLLOW_BUSINESS';
export const UNFOLLOW_BUSINESS = 'UNFOLLOW_BUSINESS';
export const BUSNIESS_LOADING = 'BUSNIESS_LOADING';
export const UPDATE_BUSINESS = 'UPDATE_BUSINESS';

/* Appointment types */
export const APPOINTMENT_LOADING = 'APPOINTMENT_LOADING';
export const GET_BUSINESS_APPOINTMENTS = 'GET_BUSINESS_APPOINTMENTS';
export const TODAY_READY_APPOINTMENTS = 'TODAY_READY_APPOINTMENTS';
export const NEXT_APPOINTMENT_ALERT = 'NEXT_APPOINTMENT_ALERT';
export const SET_APPOINTMENT_ACTIVE = 'SET_APPOINTMENT_ACTIVE';

/* Flash Messages Types */
export const SET_FLASH_MESSAGE = 'SET_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
